language: java

install:
  - mvn install -DskipTests=true

script:
  - mvn test
  
after_success:
  - mvn clean test jacoco:report coveralls:report

services:
  - postgresql
  - mysql

before_script:
  - psql -c "DROP DATABASE IF EXISTS squiggletest;" -U postgres
  - psql -c "DROP ROLE IF EXISTS squiggletest;" -U postgres
  - psql -c "CREATE USER squiggletest WITH PASSWORD '1';" -U postgres
  - psql -c "CREATE DATABASE squiggletest WITH OWNER squiggletest;" -U postgres
  - mysql -e "DROP DATABASE IF EXISTS squiggletest;"
  - mysql -e "DROP USER IF EXISTS 'squiggletest'@'localhost';"
  - mysql -e "CREATE DATABASE squiggletest;"
  - mysql -e "CREATE USER 'squiggletest'@'localhost' IDENTIFIED BY '1';"
  - mysql -e "GRANT ALL PRIVILEGES ON squiggletest.* TO 'squiggletest'@'localhost';"
